

// N_Connection
#define N_Connection_Subscribe N_ConnectionEndDevice_Subscribe_Impl
#define N_Connection_JoinNetwork N_ConnectionEndDevice_JoinNetwork_Impl
#define N_Connection_UpdateNetwork N_ConnectionEndDevice_UpdateNetwork_Impl
#define N_Connection_IsConnected N_ConnectionEndDevice_IsConnected_Impl
#define N_Connection_Reconnect N_ConnectionEndDevice_Reconnect_Impl
#define N_Connection_ReconnectUrgent N_ConnectionEndDevice_ReconnectUrgent_Impl
#define N_Connection_SetInitiatorInterPanModeOn N_ConnectionEndDevice_SetInitiatorInterPanModeOn_Impl
#define N_Connection_SetInitiatorInterPanModeOff N_ConnectionEndDevice_SetInitiatorInterPanModeOff_Impl
#define N_Connection_SetTargetInterPanModeOn N_ConnectionEndDevice_SetTargetInterPanModeOn_Impl
#define N_Connection_SetTargetInterPanModeOff N_ConnectionEndDevice_SetTargetInterPanModeOff_Impl
#define N_Connection_SetInterPanModeOn N_ConnectionEndDevice_SetInterPanModeOn_Impl
#define N_Connection_SetInterPanModeOff N_ConnectionEndDevice_SetInterPanModeOff_Impl
#define N_Connection_SetPollRate N_ConnectionEndDevice_SetPollRate_Impl
#define N_Connection_ForceNormalPolling N_ConnectionEndDevice_ForceNormalPolling_Impl
#define N_Connection_FindFreePan N_ConnectionEndDevice_FindFreePan_Impl
#define N_Connection_SendNetworkLeaveIndication N_ConnectionEndDevice_SendNetworkLeaveIndication_Impl

#define N_Connection_AssociateDiscovery N_Connection_AssociateDiscovery_Impl
#define N_Connection_AbortAssociateDiscovery N_Connection_AbortAssociateDiscovery_Impl
#define N_Connection_AssociateJoin N_Connection_AssociateJoin_Impl

#define N_Connection_TargetIsInterpanModeOn N_ConnectionEndDevice_TargetIsInterpanModeOn_Impl

// N_LinkTarget
#define N_LinkTarget_Subscribe N_LinkTarget_Subscribe_Impl
#define N_LinkTarget_SetTargetType N_LinkTarget_SetTargetType_Impl
#define N_LinkTarget_SetTouchlinkPriority N_LinkTarget_SetTouchlinkPriority_Impl
#define N_LinkTarget_AllowStealing N_LinkTarget_AllowStealing_Impl

// S_Nv
#  define S_Nv_EraseAll S_Nv_EraseAll_Impl

// N_Cmi
#  define N_Cmi_Subscribe N_Cmi_Subscribe_Impl
#  define N_Cmi_StartNetworking N_Cmi_StartNetworking_Impl
#  define N_Cmi_StartRouter N_Cmi_StartRouter_Impl
#  define N_Cmi_SetMacChannel N_Cmi_SetMacChannel_Impl
#  define N_Cmi_UpdateNetworkChannel N_Cmi_UpdateNetworkChannel_Impl
#  define N_Cmi_NetworkDiscovery N_Cmi_NetworkDiscovery_Impl
#  define N_Cmi_SendLinkStatus N_Cmi_SendLinkStatus_Impl
#  define N_Cmi_Join N_Cmi_Join_Impl
#  define N_Cmi_ResetNetworkSettings N_Cmi_ResetNetworkSettings_Impl
#  define N_Cmi_GetNetworkParams N_Cmi_GetNetworkParams_Impl
#  define N_Cmi_GetParentInfo N_Cmi_GetParentInfo_Impl
#  define N_Cmi_SwitchNetworkKey N_Cmi_SwitchNetworkKey_Impl
#  define N_Cmi_GetTotalTransmissions N_Cmi_GetTotalTransmissions_Impl
#  define N_Cmi_EnergyDetectScan N_Cmi_EnergyDetectScan_Impl
#  define N_Cmi_SendLeaveIndication N_Cmi_SendLeaveIndication_Impl
#  define N_Cmi_ProcessLeaveIndication N_Cmi_ProcessLeaveIndication_Impl
#  define N_Cmi_SendUpdateDevice N_Cmi_SendUpdateDevice_Impl
#  define N_Cmi_DataRequest N_Cmi_DataRequest_Impl
#  define N_Cmi_SetZllLinkKeyAsPrimary N_Cmi_SetZllLinkKeyAsPrimary_Impl
#  define N_Cmi_UseNwkMulticast N_Cmi_UseNwkMulticast_Impl
#  define N_Cmi_InitMacLayer N_Cmi_InitMacLayer_Impl
#  define N_Cmi_SetPollRateForTimePeriod N_Cmi_SetPollRateForTimePeriod_Impl

// N_PacketDistributor
#define N_PacketDistributor_RegisterEndpoint  N_PacketDistributor_RegisterEndpoint_Impl

//N_Hac
#define N_Hac_RegisterEndpoint N_Hac_RegisterEndpoint_Impl

#define N_Zdp_SendMgmtPermitJoiningReq N_Zdp_SendMgmtPermitJoiningReq_Impl

